name: ScanUp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        python-version: [3.8,3.8,3.8,3.8,3.9,3.8,3.8,3.8,3.8,3.9,3.8,3.8,3.8,3.8,3.9,3.8,3.8,3.8,3.8,3.9,3.8,3.9,3.8,3.9]
        update-version: [OS]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        echo "done"